version: '3.4'

services:

  jupyterlab:
    image: sensorium
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
    environment:
      - JUPYTER_PASSWORD=
 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]